name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: Main
        uses: lowlighter/metrics@master
        if: ${{ success() || failure() }}
        with:
          filename: main.metrics.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          # appearance mode
          base: header
          # begin plugins
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_languages_ignored: html, css, tex, less
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_lines: yes
          commits_authoring: GalaxySH, Rooskie, stefan@hauge.rocks, PolyversialMind@gmail.com, polyversialmind@gmail.com, GalaxySH6589@gmail.com, GreenMesa
          config_order: base.header, isocalendar, languages, notable, habits, topics, lines
          config_timezone: America/Chicago
          repositories_affiliations: collaborator
      - name: Personal
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: personal.metrics.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: metadata
          plugin_achievements: yes
          plugin_achievements_threshold: B       # Display achievements with rank B or higher
          plugin_achievements_secrets: yes       # Display unlocked secrets achievements
          plugin_achievements_ignored: octonaut  # Hide octonaut achievement
          plugin_achievements_limit: 0
          config_order: achievements, music
          config_timezone: America/Chicago
